name: vocab

services:

  backend:
    container_name: vocab-backend
    build: ../vocab-server/
    environment:
      - ConnectionStrings__PostgreSql=${BACKEND_POSTGRES_CONN_STRING}
      - ConnectionStrings__HangfireConnection=${BACKEND_HANGFIRE_DB_CONN_STRING}
      - Keycloak__auth-server-url=${BACKEND_KC_URL}
      - Keycloak__realm=${BACKEND_KC_REALM}
      - Keycloak__resource=${BACKEND_KC_CLIENT_ID}
      - Keycloak__credentials__secret=${BACKEND_KC_CLIENT_SECRET}
      - Cors__Origins=${BACKEND_CORS_ORIGINS}
      - Auth__ValidIssuers=${BACKEND_AUTH_VALID_ISSUERS}
    # volumes:
    #   - backend_vol:/app/logs:rw
    networks:
      vocab_net:
        ipv4_address: 172.18.2.2
    ports:
      - "5000:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/healthz || exit 1" ]
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 15s
    # ---------------------------------------------

    # frontend:
    #   container_name: vocab-frontend
    #   # build: ../vocab-client/
    #   image: hello-world
    #   networks:
    #     vocab_net:
    #       ipv4_address: 172.18.2.3
    #   ports:
    #     - "3000:3000"
    #   depends_on:
    #     backend:
    #       condition: service_healthy

networks:
  vocab_net:
    ipam:
      config:
        - subnet: 172.18.2.0/24

# volumes:
#   backend_vol:
