name: vocab

services:

  auth:
    container_name: auth
    image: quay.io/keycloak/keycloak:25.0.2
    environment:
      - KC_DB=${KC_DB}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_DB_URL=${KC_DB_URL}
      - KC_PROXY_HEADERS=xforwarded
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
    networks:
      vocab_net:
        ipv4_address: 172.18.0.4
    ports:
      - "8080:8080"
    command: [ "start" ]
# ---------------------------------------------
  backend:
    image: backend
    build: ../vocab-server/
    environment:
      - ConnectionStrings__PostgreSql=${BACKEND_POSTGRES_CONN_STRING}
      - ConnectionStrings__HangfireConnection=${BACKEND_HANGFIRE_DB_CONN_STRING}
      - Keycloak__auth-server-url=${BACKEND_KC_URL}
      - Keycloak__realm=${BACKEND_KC_REALM}
      - Keycloak__resource=${BACKEND_KC_CLIENT_ID}
      - Keycloak__credentials__secret=${BACKEND_KC_CLIENT_SECRET}
      - Cors__Origins=${BACKEND_CORS_ORIGINS}
    networks:
      vocab_net:
        ipv4_address: 172.18.0.2
    ports:
      - "5000:5000"
    depends_on:
      - auth
# ---------------------------------------------
  # frontend:
  #   networks:
  #     vocab_net:
  #       ipv4_address: 172.18.0.3
  #   depends_on:
  #     - backend
  #     - auth

networks:
  vocab_net:
    ipam:
      config:
        - subnet: 172.18.0.0/16
